In [1]:
# numpy array 
# numpy with ndarray used as the primary data structure for representing data
# create array
from numpy import array
# create array
l = [1.0, 2.0, 3.0]
a = array(l)
# display array
print(a)
# display array shape
print(a.shape)
# display array data type
print(a.dtype)

[1. 2. 3.]
(3,)
float64


In [19]:
# data type at python
type(1234)

int

In [18]:
type(18.80)

float

In [20]:
type(6+4j)

complex

In [21]:
type("Hello World")

str

In [22]:
type([1,2,3,4])

list

In [23]:
type({1:"one", 2:"two", 3:"three"})

dict

In [26]:
# create empty array
from numpy import empty
g = empty([3,3])
print(g)
# create zerro array
from numpy import zeros
g_1 = zeros([3,5])
print(g_1)

[[1.06249740e-312 0.00000000e+000 1.06395697e+224]
 [4.25330994e+174 4.67104847e-062 2.17435387e-076]
 [8.00377178e+169 3.89681814e-086 6.27207943e-310]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [33]:
# help('numpy')
# help('zeroes')

In [34]:
from numpy import ones
g_2 = ones([5])
print(g_2)

[1. 1. 1. 1. 1.]


In [1]:
# Combining Arrays
from numpy import array
from numpy import vstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# vertical stack
a3 = vstack((a1,a2))
print(a3)
print(a3.shape)

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
(2, 3)


In [2]:
# horizontal stack
from numpy import array
from numpy import hstack
# create first array
a1 = array([1,2,3])
print(a1)
# create second array
a2 = array([4,5,6])
print(a2)
# create horizontal stack
a3 = hstack((a1,a2))
print(a3)
print(a3.shape)


[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
(6,)


In [3]:
# One-Dimensional List to Array
from numpy import array
# list of data
data = [11,22,33,44,55]
# array of data
data = array(data)
print(data)
print(type(data))

[11 22 33 44 55]
<class 'numpy.ndarray'>


In [6]:
# Two-Dimensional List of Lists to Array
from numpy import array
# list of data
data = [[11,22],[33,44],[55,66]]
# array of data
data = array(data)
print(data)
print(data.shape)
print(type(data))

[[11 22]
 [33 44]
 [55 66]]
(3, 2)
<class 'numpy.ndarray'>


In [8]:
# array indexing
# One-Dimensional Indexing
from numpy import array
# define array
data = array([11,22,33,44,55])
# index data
print(data)
print(data[0])
print(data[4])



[11 22 33 44 55]
11
55


In [1]:
# index array out of bounds
from numpy import array
# define array
data = array([11,22,33,44,55])
# index data
print(data[5])

IndexError: index 5 is out of bounds for axis 0 with size 5

In [2]:
# negative array indexing
from numpy import array 
# define array
data = array([11,22,33,44,55])
# index data
print(data[-1])
print(data[-5])

55
11


In [4]:
# Two-Dimensional Indexing
# index two-dimensional array
from numpy import array
# define array
data = array([[11,22], [33,44], [55,66]])
# index data
print(data[0,0])

11


In [5]:
print(data.shape)

(3, 2)


In [6]:
print(data[0,1])

22


In [9]:
print(data[1,1])

44


In [11]:
print(data[0,2])

IndexError: index 2 is out of bounds for axis 1 with size 2

In [12]:
print(data[3,1])

IndexError: index 3 is out of bounds for axis 0 with size 3

In [13]:
print(data[2,1])

66


In [14]:
print(data[2,0])

55


In [15]:
# index row of two-dimensional array
from numpy import array
# define array
data = array([[11,22],[33,44],[55,66]])
# index data
print(data[0,])

[11 22]


In [17]:
print(data[1,])

[33 44]


In [18]:
# array slicing
# One-Dimensional Slicing
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[:])

[11 22 33 44 55]


In [19]:
print(data)

[11 22 33 44 55]


In [20]:
# slice a subset of a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[0:1])

[11]


In [24]:
print(data[0:2])
print(data[0:3])
print(data[0:4])
print(data[0:5])

[11 22]
[11 22 33]
[11 22 33 44]
[11 22 33 44 55]


In [22]:
print(data.shape)

(5,)


In [25]:
print(data[1:2])
print(data[1:3])
print(data[1:4])

[22]
[22 33]
[22 33 44]


In [27]:
# negative slicing of a one-dimensional array
from numpy import array
# define array
data = array([11,22,33,44,55])
print(data[-2:])
print(data[-3:])
print(data[-4:])

[44 55]
[33 44 55]
[22 33 44 55]


In [28]:
# Two-Dimensional Slicing
# split input and output data
from numpy import array
# define array
data = array([[11,22,33],[44,55,66],[77,88,99]])
# seperate data
X, y = data[:,:-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [37]:
print(data[:,-1])
print(data[:,-2])
print(data[:,-3])

[33 66 99]
[22 55 88]
[11 44 77]


In [36]:
print(data.shape)

(3, 3)


In [41]:
data_1 = data[:,:-1]
print(data_1)
data_2 = data[:,:-2]
print(data_2)

[[11 22]
 [44 55]
 [77 88]]
[[11]
 [44]
 [77]]


In [43]:
data_3 = data[:,:-0]
print(data_3)

[]


In [2]:
# Split Train and Test Rows
# we can split the dataset at the contrived split point of 2
from numpy import array
# define array
data = array([[11,22,33],[44,55,66],[77,88,99]])
# separate data
split = 2
train, test = data[:split,:], data[split:,:]
print(train) #data baris pertama kedua 
print(test) # data baris terakhir

[[11 22 33]
 [44 55 66]]
[[77 88 99]]


In [4]:
# Data Shape
# menunjukan dimensi array dari suatu data
# one-dimensional array
from numpy import array 
# define array 
data = array([11,22,33,44,55])
print(data.shape)

(5,)


In [6]:
# Data shape
# two-dimensional array
data=[[11,22],[33,44],[55,66]]
data=array(data)
print(data.shape)
print('Rows:%d'% data.shape[0])
print('Cols:%d'% data.shape[1])

(3, 2)
Rows:3
Cols:2


In [2]:
# Reshape 1D to 2D Array
from numpy import array
data = array([11,22,33,44,55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0],1))
print(data.shape)

(5,)
(5, 1)


In [3]:
# reshape 2D array to 3D
from numpy import array
data = [[11,22],[33,44],[55,66]]
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)

(3, 2)
(3, 2, 1)


In [2]:
# array arithmetic between arrays with a dierent shape or size
# array arithmetic dalam numpy dinamakan sebagai array broadcasting
from numpy import array
a = array([1,2,3])
print(a)
b = 2
print(b)
# broadcast
c = a + b
print(c)


[1 2 3]
2
[3 4 5]


In [4]:
# Scalar dan 2-Dimensional Array
from numpy import array
A = array([[1,2,3], [1,2,3]])
print(A)
b = 2
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
2
[[3 4 5]
 [3 4 5]]


In [6]:
# broadcast 1-Dimensional to 2-dimensional array
# broadcast array tidak bekerja untuk dimensi kolom yang berbeda
from numpy import array
# 2-Dimensional array
A = array([[1,2,3],[1,2,3]])
print(A)
# 1-Dimensional array
b = array([1,2,3])
print(b)
C = A + b
print(C)

[[1 2 3]
 [1 2 3]]
[1 2 3]
[[2 4 6]
 [2 4 6]]


In [15]:
# references 
url = "https://docs.scipy.org/doc/numpy-1.13.0/reference/"
url = "https://docs.scipy.org/doc/numpy-1.13.0/user/basics.broadcasting.html"
url = "https://eli.thegreenplace.net/2015/broadcasting-arrays-in-numpy/"
url = "https://www.tensorflow.org/xla/broadcasting"